//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimmEstimatingTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIMM_DevEntities : DbContext
    {
        public AIMM_DevEntities()
            : base("name=AIMM_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estimate> Estimates { get; set; }
        public virtual DbSet<EstimateCalculator> EstimateCalculators { get; set; }
        public virtual DbSet<EstimateProjectType> EstimateProjectTypes { get; set; }
        public virtual DbSet<EstimateSubCalculator> EstimateSubCalculators { get; set; }
    }
}
