//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimmEstimatingTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        public int EstimateId { get; set; }
        public int JobId { get; set; }
        public int ProjectNo { get; set; }
        public int Sequence { get; set; }
        public int EstimateCalculatorId { get; set; }
    }
}
